---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverblue-custom
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44 # latest is also supported if you want new updates ASAP

modules:

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - zsh
        - stow
        - curl
        - rclone
        - nmap
        - dig
        - mc
        - libvirt
        - virt-manager
        - qemu-kvm
        - wireguard-tools
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - nvtop
        - htop

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          # Browser
          - org.mozilla.firefox
          - org.chromium.Chromium      
          # Remote Sessions
          - org.remmina.Remmina
          # Editor
          - com.visualstudio.code
          # Notes
          - net.cozic.joplin_desktop
          # Office Suite
          - org.libreoffice.LibreOffice
          # Calculator
          - org.gnome.Calculator
          # Multimedia
          - org.videolan.VLC

  - type: systemd
    system:
      enabled:
        - podman

  - type: signing
