---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: silverblue-custom
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:

  - type: files
    files:
      - source: system
        destination: /

  ### SOME PACKAGES ARE ALREADY PRESENT BUT I PREFER TO FORCE IT ###
  
  - type: dnf
    install:
      packages:
        - zsh
        - stow
        - curl
        - rclone
        - nmap
        - dig
        - mc
        - dos2unix
        - libvirt
        - virt-manager
        - qemu-kvm
        - wireguard-tools
        - jq
        - yq
        - p7zip
        - p7zip-plugins
        - rar
        - unrar
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - nvtop
        - htop

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          # Browser
          - org.mozilla.firefox
          - org.chromium.Chromium
          # Remote Sessions
          - org.remmina.Remmina
          # Editor
          - com.visualstudio.code
          # Notes
          - net.cozic.joplin_desktop
          # PDF
          - org.gnome.Evince
          # Office Suite
          - org.libreoffice.LibreOffice
          # Calculator
          - org.gnome.Calculator
          # Multimedia
          - org.videolan.VLC
          # Calls
          - com.github.IsmaelMartinez.teams_for_linux
          # Backup
          - org.gnome.World.PikaBackup
          # Vault
          - com.bitwarden.desktop
          # Archive
          - org.gnome.FileRoller
          # Clock
          - org.gnome.clocks
          # Disk Usage
          - org.gnome.baobab
          # Resources
          - net.nokyan.Resources

  - type: script
    scripts:
      - customize.sh

  - type: systemd
    system:
      enabled:
        - podman
  
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
        - Hack
        - SourceCodePro
        - Terminus
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter
  
  - type: signing
